name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Update if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up GitHub Pages
    - name: Setup Pages
      uses: actions/configure-pages@v3

    # Deploy to GitHub Pages
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  # Deploy branch
        folder: food-delivery  # Change to your folder containing index.html, if not the root
